### PR TITLE
Reconstruction/ou_inference method

### PR DESCRIPTION
**Pull request by charlesmurphy1**
Implementation of Orstein-Uhlenbeck network inference based on [P. Barucca, Phys. Rev. E 90, 062129 (2014)]. I also compared the inference given by my implementation with that of the original author (https://github.com/paolobarucca/OUinference) and it provides the same output.

### CODE REVIEW

**Comment by tlarock** [comment]
Here are the docs for `from_numpy_array`: https://networkx.github.io/documentation/stable/reference/generated/networkx.convert_matrix.from_numpy_array.html

**Comment by charlesmurphy1** [comment]
Got it, I did the changes, but I think I did something wrong within git.

**Comment by tlarock** [comment]
I think I might have given the wrong code (I don't think we needed the `.convert_matrix.` part)- let's see if the checks pass this time.

**Comment by charlesmurphy1** [comment]
Within my version of networkx at least, I cannot find neither nx.convert_matrix.from_numpy_array or nx.from_numpy_array. I have networkx version 1.11.

**Comment by charlesmurphy1** [comment]
It should be fine now on this front.

**Pull request merged**
