### PR TITLE
Two small fixes and black file auto-formatting.

### PR DESCRIPTION
**Pull request by djpasseyjr**
Hi, I ran into a bug in the continuous time Lotka-Volterra model and I fixed it. I ran the black  auto-formatter as well. Additionally, when I ran the tests I caught a depreciated `networkx` method and fixed it: `nx.from_scipy_sparse_matrix -> nx.from_scipy_sparse_array`. 

As far as I can tell all tests pass!
DJ

### CODE REVIEW

**Review by leotrs — COMMENTED** [review]
@djpasseyjr Thank you for your contribution! Always appreciated :)

@sdmccabe The CI is not running because of some python version weirdness. Do you have time to take a look?

**Comment by sdmccabe** [comment]
@djpasseyjr Thanks for this!

@leotrs CI issue seems to be https://github.com/actions/setup-python/issues/544#issuecomment-1320091667.

My instinct is to just drop 3.6; it's end-of-life anyway. (And we should add 3.10/3.11 coverage.) Sound good to you?

**Comment by leotrs** [comment]
Affirmative.

**Review by leotrs — APPROVED** [review]
Thanks again @djpasseyjr. Thanks to @sdmccabe and #329 now all tests pass.

**Pull request merged**
