### PR TITLE
A bunch of distances based on the Laplacian spectrum

### PR DESCRIPTION
**Pull request by gstonge**
Due to the fact that many spectral distances for the Laplacian matrix uses : 
- Different kernels to convolve the discrete spectrum to obtain a continuous one
- The normalized and unormalized version of the matrix
- Different metrics to compare the continuous spectra
The class LaplacianSpectralMethod allows one to tune all of the above in a same class. At the moment, one has 8 possible measures (normalized or not, normal or lorentzian kernel, euclidean and jensen-shannon distance). Defaults are normalized, normal kernel and jensen-shannon, based upon the first paper referenced in the docstring.

### CODE REVIEW

**Comment by sdmccabe** [comment]
The test failures seem to be due to the fact that matplotlib is not in `requirements.py`. Since matplotlib is imported but not used in `laplacian_spectral_method.py`, I think dropping that import is probably the quickest fix.

**Comment by leotrs** [comment]
@gstonge Great work here! I like what you are doing. I see a number of ways this can go. One is of course adding more ways of comparing the spectra once it's computed. For example, there are a few ways of comparing the empirical (discrete) spectrum. That's probably better left for a later version though.

Before merging, I wanted to ask - how tough do you think it's going to be to implement this using sparse matrices? Using sparse matrices would accelerate all of this greatly and we would be able to use this on large networks too. Using sparse matrices also opens up the possibility of not using all eigenvalues, but only the largest `k` eigenvalues. It would be an interesting experiment in itself to see how these distance measures change when the number of eigenvalues used changes.

if it'd take too much time/code to use sparse matrices, I can merge this and we can work on a separate PR for that.

**Comment by gstonge** [comment]
> @gstonge Great work here! I like what you are doing. I see a number of ways this can go. One is of course adding more ways of comparing the spectra once it's computed. For example, there are a few ways of comparing the empirical (discrete) spectrum. That's probably better left for a later version though.
> 
> Before merging, I wanted to ask - how tough do you think it's going to be to implement this using sparse matrices? Using sparse matrices would accelerate all of this greatly and we would be able to use this on large networks too. Using sparse matrices also opens up the possibility of not using all eigenvalues, but only the largest `k` eigenvalues. It would be an interesting experiment in itself to see how these distance measures change when the number of eigenvalues used changes.
> 
> if it'd take too much time/code to use sparse matrices, I can merge this and we can work on a separate PR for that.

Great idea! For now I have just implemented the sparse matrix decomposition at the end if "k" is specified, by transforming the dense laplacian matrix into a sparse one. For large networks, I assume that the eigenvalue decomposition should be the bottleneck, and that the manipulations with dense matrices before should not cause too much problem. If it reveals to be too slow, we can still rework it to work only with sparse matrices. I has to be noted though that "eigsh" from the scipy.sparse.linalg package cannot be used to obtain all eigenvalues, and "eigh" or "eigvalsh" cannot be used with sparse matrices.

**Comment by sdmccabe** [comment]
Reading the code, it looks like you handle this case, but can you confirm that these methods work on directed graphs? We ran into an issue with resistance perturbation failing because it was assuming the Laplacian would always be symmetric (see #105).

**Comment by leotrs** [comment]
Sorry for the lateness, but this is a great contribution @gstonge !

**Comment by gstonge** [comment]
> Reading the code, it looks like you handle this case, but can you confirm that these methods work on directed graphs? We ran into an issue with resistance perturbation failing because it was assuming the Laplacian would always be symmetric (see #105).

Sorry for the delay, maybe you already verified it, but yes I tested it on directed graph and it works!

**Pull request merged**
