### PR TITLE
Add checks.py with ensure_undirected function

### PR DESCRIPTION
**Pull request by tlarock**
Some methods require an undirected network. This PR adds a utility function, `utilities.ensure_undirected(G)`, that checks whether an input `networkx` graph is directed. If it is, the network is coerced using `DiGraph.to_undirected()`, and a warning is raised to tell the user this is happening. If it is already undirected, the object is returned as is.

One potential point of confusion could be someone not reading the docstring and trying to use this to test an adjacency matrix for symmetry. `networkx` will throw an error if they do this, but just want to note that we may want to have similar functionality for adjacency matrices in the future.

### CODE REVIEW

**Comment by sdmccabe** [comment]
I don't like the name `checks.py`.

**Comment by tlarock** [comment]
I'll gladly change it if you have a suggestion....

**Comment by sdmccabe** [comment]
I would probably just move the functions into graphs.py.

**Comment by sdmccabe** [comment]
Merging but I do think it would be cleaner to move this into `graphs.py` at some point.

**Pull request merged**
