### PR TITLE
refactor standardize.py

### PR DESCRIPTION
**Pull request by leotrs**
A couple of things are included in this PR:
1. The `dis_list` variable was not needed as it was only used to compute mean and standard deviation, which can be done directly from `dis_mat`.
2. There was a typo in line 64, where `dis` was used instead of `dis_mat`.
3. Changed `edge_probability` to `prob` for the sake of shorter lines.
3. IMPORTANT: Computation time can be halved if we assume that all distance functions are symmetric. In that case, we need only compute the upper triangular entries of `dis_mat`. However, this is conditioned on all distances in `netrd/distances` being symmetric. *Are we sure they all are?*

### CODE REVIEW

**Comment by tlarock** [comment]
Some of this was discussed in the original PR (https://github.com/netsiphd/netrd/pull/118#discussion_r258715113) but we didn't open new issues, prob could have. 

It is written as it is because (a) we didn't want to make the assumption that the distances are all always going to be symmetric and (b) computing the mean of the entire matrix includes the diagonal, which adds bias to the average since seeing the same graph twice is extremely unlikely when sampling from the ensemble (as noted in the docstring). Computing `dis_mat.T.mean()` does not exclude the diagonal, does it?

**Comment by leotrs** [comment]
Ah, apologies, I missed that part of the discussion. 

(a) Why don't we want to do that? Even if we don't enforce it, it might be a healthy exercise to discuss it.
(b) You're right, didn't think about the bias. Using `dis_mat.mean()` does not exclude the diagonal, but the fix is to multiply by the appropriate normalization, which incurs in `O(1)` added time, as opposed to using `dis_list` which uses `O(samples^2)` added memory. I might be over optimizing here... though it really depends on how long it takes to run the distances themselves, rather than the number of samples.

**Comment by tlarock** [comment]
(a) Agreed this should be figured out. @hartle and I wrote this code at a weekly meeting and never got around to opening any issues about it, I guess with an implicit expectation that they would come up when we tried to use it (which is maybe what's happening now?). I don't have strong feelings/desires to go figure out whether distances are symmetric myself, but somebody should think about it.
(b) As you point out, if there is going to be an issue with this function, it is almost surely going to be the time complexity of sampling the networks and computing the distances, rather than the space complexity. But it doesn't hurt to optimize for space, feel free to update it to not use the list. There's no other reason for it than it was a straightforward way to handle it without a lot of thought/`numpy` slicing.

**Comment by leotrs** [comment]
Now that you mention slicing, a probably clearer fix is to use upper triangular indices:

```
indices = np.triu_indices(n, 1)
return dis_mat[indices].mean(), dis_mat[indices].std(), dis_mat
```

Which would do what we want without the added space. Though we should implement this only after we have figured out (a). cc @sdmccabe @hartle.

**Comment by sdmccabe** [comment]
If we want to say okay, symmetric measures only, we should add a test for that in the test suite. That would hopefully also help us flag if anything of the existing measures are not symmetric.

**Comment by leotrs** [comment]
One way I see of testing this is by enforcing that `abs(dist(G1, G2) - dist(G2, G1) < eps` for some small number `eps`. The problem is choosing what's a reasonable `eps`. Its value should probably vary from one method to another.

Another way of doing it is by enforcing `abs(dist(G1, G2) - dist(G2, G1) < eps * norm` where `norm` is the average distance between G(n,p) networks, as determined by `standardize.py`. We still have to choose `eps` but it would at least be a global parameter (hopefully?)

**Comment by sdmccabe** [comment]
FWIW, this simple test passes:

```python

def test_symmetry():
    """The distance between two graphs must be symmetric."""

    G1 = nx.barabasi_albert_graph(100, 4)
    G2 = nx.fast_gnp_random_graph(100, 0.1)

    for obj in distance.__dict__.values():
        if isinstance(obj, type) and BaseDistance in obj.__bases__:
            dist1 = obj().dist(G1, G2)
            dist2 = obj().dist(G2, G1)
            assert np.isclose(dist1, dist2)

```

**Comment by sdmccabe** [comment]
Can you change this to use the full matrix (i.e., assume asymmetry) for now? Let's move the discussion of the symmetry issue to #136.

**Pull request merged**
