### PR TITLE
Drop eigenvalues with negative complex part in NBD

### PR DESCRIPTION
**Pull request by sdmccabe**
See discussion in #296.

### CODE REVIEW

**Comment by sdmccabe** [comment]
This doesn't actually seem to fix the labelling issue; perhaps I'm doing it wrong.

```
In [2]: from netrd.distance import NonBacktrackingSpectral 
   ...: import networkx as nx 
   ...: import numpy as np 
   ...:  
   ...: md = 0. 
   ...: for _ in range(100): 
   ...: ^IG1 = nx.fast_gnp_random_graph(150, .1) 
   ...: ^IG2 = nx.from_numpy_array(nx.to_numpy_array(G1, nodelist=np.random.permutation(150))) 
   ...: ^Id = NonBacktrackingSpectral() 
   ...: ^Idist = d.dist(G1, G2, include_negative_evals=False) 
   ...: ^Iif dist > md: 
   ...: ^I^Imd = dist 
   ...: print(md)                                                                                                                                                      
0.08290333189771043

In [3]: from netrd.distance import NonBacktrackingSpectral 
   ...: import networkx as nx 
   ...: import numpy as np 
   ...:  
   ...: md = 0. 
   ...: for _ in range(100): 
   ...: ^IG1 = nx.fast_gnp_random_graph(150, .1) 
   ...: ^IG2 = nx.from_numpy_array(nx.to_numpy_array(G1, nodelist=np.random.permutation(150))) 
   ...: ^Id = NonBacktrackingSpectral() 
   ...: ^Idist = d.dist(G1, G2, include_negative_evals=True) 
   ...: ^Iif dist > md: 
   ...: ^I^Imd = dist 
   ...: print(md)                                                                                                                                                      
0.07619989674172042
```

**Comment by leotrs** [comment]
So the same thing as before may be happening where the graph has two eigenvalues with the same magnitude, and the eigensolver sometimes returns one but other times the other. For example if the graph has `-1` and `+1` as eigenvalues.

Honestly, I would just make this a random test.

**Comment by sdmccabe** [comment]
From @leotrs:
> Make #299 a randomized test.

I'll try to get to this in a couple days.

**Comment by sdmccabe** [comment]
I modified the `test_isomorphic_input()` in this way:
```python
    for label, obj in distance.__dict__.items():
        print(label)
        if (
            isinstance(obj, type)
            and BaseDistance in obj.__bases__
            and label not in EXCLUDED_DISTANCES
        ):
            dist = obj().dist(G1, G2)
            assert np.isclose(dist, 0.0, atol=1e-3)
        elif label == "NonBacktrackingSpectral":
            # NOTE: A special case; see the discussion in #296 and #299. If NBD
            # fails to pass this test, it can be due to the sign of the
            # eigenvalues returned. We get around this by requesting the normal
            # number of eigenvalues, testing, and then if it fails we get one
            # more eigenvalue and test again.
            nbd = obj()
            dist = nbd.dist(G1, G2)
            try:
                assert np.isclose(dist, 0.0, atol=1e-3)
            except AssertionError:
                print("NBD: using extra eigenvalue")
                topk = len(nbd['results']['vals1'][0])
                new_dist = nbd.dist(G1, G2, topk=topk+1)
                assert np.isclose(new_dist, 0.0, atol=1e-3)
```

This makes it fail less often but it still fails occasionally (10% of the time?). Thoughts @leotrs?

**Comment by leotrs** [comment]
LGTM

**Comment by sdmccabe** [comment]
Should we just accept a small number of test failures here? Maybe merge as-is and revisit if it ends up being annoying?

**Comment by leotrs** [comment]
Merge as is and revise later.

#TestInProduction

**Comment by sdmccabe** [comment]
@leotrs sorry, was a draft before; can you approve?

**Comment by sdmccabe** [comment]
actually, don't merge yet, small bug.

**Review by leotrs — APPROVED** [review]

**Comment by sdmccabe** [comment]
What if we took _all_ the eigenvalues instead of N+1? Would that change anything? It still fails a bit too often, I think.

**Comment by leotrs** [comment]
That would help but it would take a bit longer

**Comment by sdmccabe** [comment]
Still fails too often. Tempted to abandon ship on this one and just throw NBD back into the set of `EXCLUDED_DISTANCES`.

**Comment by leotrs** [comment]
Yikes. Not sure what's going on. I'd suggest you keep the new `ignore_negative_values` but also forget about testing this :shrug:

**Comment by sdmccabe** [comment]
Can you eyeball the include_negative_evals logic one last time? It's been a while. Also, regardless I'll need to fix the docstrings, they're exactly wrong.

**Comment by leotrs** [comment]
I just did LGTM

**Pull request merged**
