### PR TITLE
Add test coverage for invariance under vertex relabeling

### PR DESCRIPTION
**Pull request by sdmccabe**
This adds a test to `test_distance` to assert that the distance between a graph and a copy of that graph with its node labels permuted should be zero. This is not something we are strictly enforcing as a requirement but we should have test coverage for it for documentation purposes; i.e., if we have a distance that is not invariant here it should be documented, and by enforcing it in test coverage we hopefully guarantee that the ones we expect to be invariant are. In the current commit I've excluded all the distances for which the test failed. Some of these, like `Hamming` and `JaccardDistance`, were unsurprising to me, but others were. We should make sure that this list represents our prior knowledge before merging.

### CODE REVIEW

**Comment by sdmccabe** [comment]
Said this offline a few days ago, but I'm reasonably confident the `QuantumJSD` result is because of numerical issues. Even for pretty small graphs the call to `expm()` (which is an approximation) is adding a lot of error.

```python
>>> G = nx.karate_club_graph()
>>> A1 = nx.to_numpy_array(G)
>>> A2 = nx.to_numpy_array(G, nodelist=np.random.permutation(len(G.nodes)))
>>> L1 = laplacian(A1)
>>> L2 = laplacian(A2)
>>> (np.sort(expm(L2).ravel()) - np.sort(expm(L1).ravel())).sum() 
-4.5126057557354216e-08
```


```python
>>> G = nx.fast_gnp_random_graph(150, 0.1)
>>> A1 = nx.to_numpy_array(G)
>>> A2 = nx.to_numpy_array(G, nodelist=np.random.permutation(len(G.nodes)))
>>> L1 = laplacian(A1)
>>> L2 = laplacian(A2)
>>> (np.sort(expm(L2).ravel()) - np.sort(expm(L1).ravel())).sum() 
 -0.000533777114469558
```

```python
>>> G = nx.fast_gnp_random_graph(150, 0.1)
>>> A1 = nx.to_numpy_array(G)
>>> A2 = nx.to_numpy_array(G, nodelist=np.random.permutation(len(G.nodes)))
>>> L1 = laplacian(A1)
>>> L2 = laplacian(A2)
>>> (np.sort(expm(L2).ravel()) - np.sort(expm(L1).ravel())).sum() 
4.422126459997389e+16
```

**Comment by sdmccabe** [comment]
The remaining mystery is the results for `NonBacktrackingSpectral`, `DistributionalNBD`, and `LaplacianSpectral` with a Gaussian kernel. I think these are all probably similar stories to `QuantumJSD`, but I want to explore that before merging.

**Comment by sdmccabe** [comment]
I also don't think `DMeasure` is. I haven't actually managed to reproduce it failing; it returns a non-zero value but it's typically something like `1e-9`.

**Comment by sdmccabe** [comment]
Ugh, I hate it when the tests run locally and fail on Travis.

**Comment by sdmccabe** [comment]
When `DMeasure` fails, it seems to be with:
```
tests/test_distance.py::test_isomorphic_input
  /home/main/git/sdmccabe/netrd/netrd/distance/dmeasure.py:147: RuntimeWarning: invalid value encountered in sqrt
    third_term = 0.5 * (np.sqrt(first_jsd) + np.sqrt(second_jsd))
```

**Comment by sdmccabe** [comment]
Ok, the issue here is that in lines 116-119 of `dmeasure.py`, we have:

```python
g1_nnd, g1_pdfs = network_node_dispersion(G1)
g2_nnd, g2_pdfs = network_node_dispersion(G2)

first_term = np.sqrt(js_divergence(g1_pdfs, g2_pdfs))
```

Because the graphs are isomorphic, they have the same NND. So the JSD between them is zero, but because of floating-point error, it's sometimes returning something like `-1e-17`, which is causing the square root of the JSD to be `nan`.

I don't love either of these solutions, but I see two:

1. capture the JSD and set it zero before `first_term` is calculated.
2. modify `js_divergence` to return zero if it `isclose` to zero.

**Comment by leotrs** [comment]
I vote for 2.

This should probably be done for other functions as well (though let's not go on that hunt just now).

**Comment by sdmccabe** [comment]
Is there any risk to doing 2? I can't think of one, since it shouldn't be giving us negative values anyway.

**Comment by leotrs** [comment]
If a number if within 1e-8 of 0 then it is zero. Regardless of sign.

**Comment by sdmccabe** [comment]
`NonBacktrackingSpectral` still occaisionally fails this test. The largest distance I've seen is 0.09, which I think is too large for us to address by just upping the `atol`.

**Comment by sdmccabe** [comment]
I think I want to be done with this PR for a while. I'd suggest:

1. Merge as-is.
2. Add documentation to `NonBacktrackingSpectral`, `DistributionalNBD`, and `QuantumJSD` noting the isomorphism/floating-point issues.
3. Open an issue to remember to investigate those more later.

**Comment by leotrs** [comment]
If you're able to provide a minimal working example that replicates the error, I'd love to see that. The distance does not use all of the eigenvalues, only some, right? Sometimes it happens that there are two eigenvalues with the same magnitude so the eigensolver returns one sometimes and the other some other times.

**Comment by sdmccabe** [comment]
```python
md = 0.
for _ in range(100):
	G1 = nx.fast_gnp_random_graph(150, .1)
	G2 = nx.from_numpy_array(nx.to_numpy_array(G1, nodelist=np.random.permutation(150)))
	d = NonBacktrackingSpectral(); 
	dist = d.dist(G1, G2); 
	if dist > md:
		md = dist
```

I got `0.07` this time. Note that NBD is slow (maybe from the ortools change?) so it takes a while.

**Comment by leotrs** [comment]
Figure_1

This is a scatter plot of the eigenvalues of two graphs whose distance is 0.06 (in the complex plane). The two graphs were generated with your code. Look closely at the points at the coordinates approx `(-2, 3.1)` and `(-2, -3.1)`. One graph has one of those eigenvalues but the other one doesn't, and vice versa. In reality, both graphs have the same eigenvalues (and therefore the distance should be zero) but the eigensolver is returning either one of the pair of eigenvalues but not both. If you compute the distance with `topk` equal to one plus whatever the default is, then you will get both eigenvalues in both graphs and always get a result of zero. The problem is that for a different value of topk, different pairs of graphs will present this problem.

So there are two solutions:
1. Ignore every eigenvalue that has a negative complex part. This is something I should have done in my paper many years ago. But I didn't so.
2. If this test fails, just run it again (on the exact same graphs) but computing one more eigenvalue, and check to see if it passes.

**Comment by sdmccabe** [comment]
The former seems more principled; do you have a preference? Also, do you think the same would apply to `DistributionalNBD`?

**Comment by leotrs** [comment]
I don't have a preference, but if we do the former we should put a big warning somewhere saying that this version differs from my paper's and my reference repo's version. Which is fine by me, it's not like anyone is using them anyway :)

It is my understanding the DistributionalNBD already did this, or at least they said so in their paper. I don't know if they are doing it in the code in this repo.

**Comment by sdmccabe** [comment]
How about a parameter for `NonBacktrackingSpectral.dist` that allows for both behaviors but defaults to dropping the eigenvalues with negative complex parts?

**Comment by leotrs** [comment]
Sounds good!

**Comment by sdmccabe** [comment]
@leotrs what do you think we should do with this and #299? It got dropped pretty abruptly but it didn't seem like there was much to improve on the test here (and the stuff in #299 didn't seem to be working all that well).

**Comment by leotrs** [comment]
Merge this. Make #299 a randomized test.

**Pull request merged**
