### PR TITLE
use denser random graphs in distance tests

### PR DESCRIPTION
**Pull request by sdmccabe**
See #239.

### CODE REVIEW

**Comment by sdmccabe** [comment]
The tests are failing on denser graphs. 

```
=================================== FAILURES ===================================
_____________________________ test_directed_input ______________________________
    def test_directed_input():
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore", message="Coercing directed graph to undirected."
            )
            G = nx.fast_gnp_random_graph(100, 0.3, directed=True)
    
            for label, obj in distance.__dict__.items():
                if isinstance(obj, type) and BaseDistance in obj.__bases__:
                    dist = obj().dist(G, G)
>                   assert np.isclose(dist, 0.0)
E                   assert False
E                    +  where False = <function isclose at 0x7f8a4b1d2268>(nan, 0.0)
E                    +    where <function isclose at 0x7f8a4b1d2268> = np.isclose
test_distance.py:88: AssertionError
```

**Comment by leotrs** [comment]
Do we know which is the offending distance?

**Comment by sdmccabe** [comment]
`QuantumJSD` is the offending distance.

**Comment by sdmccabe** [comment]
My knee-jerk reaction is that `QuantumJSD` should coerce to undirected, since the definitions in the paper I think tend to mention undirected graphs, and it's using the Laplacian.

**Comment by leotrs** [comment]
Anything that uses the Laplacian should coerce undirected tho.

**Pull request merged**
