### PR TITLE
Rename entropy to entropy_from_seq 

### LINKED ISSUE #261: Clarify usage of utilities.entropy.entropy?
When I was refactoring the Dmeasure code, I looked at using our version of entropy instead of scipy's, but one is not a drop-in replacement for the other because they take different inputs - one takes a histogram and the other takes a sequence of values. It would touch a lot of files but but renaming our `entropy` to something like `entropy_from_sequence` would remove this ambiguity.

### PR DESCRIPTION
**Pull request by sdmccabe**
Resolves #261. I grepped my way through the repo and didn't see any direct uses of `netrd.utilities.entropy.entropy` so I didn't touch anything else.

### CODE REVIEW

**Comment by sdmccabe** [comment]
@chiahungyang @leotrs

**Comment by chiahungyang** [comment]
I have no objection

**Comment by leotrs** [comment]
Why do we have it if it's not being used?

**Comment by sdmccabe** [comment]
I guess there is the question: are there places in the code where we could currently use it?

**Comment by chiahungyang** [comment]
Uh I think I wrote it in case that someone wants to compute entropy from an 1D array.
I didn't use it at all......

**Pull request merged**
