### PR TITLE
Baseline spectral distance

### PR DESCRIPTION
**Pull request by gstonge**
Added the option None for the kernel in laplacian_spectral_method, resulting in the euclidean distance between the discrete spectra of the Laplacian matrices.

This is for issue #156

### CODE REVIEW

**Comment by sdmccabe** [comment]
This looks good. We should write a separate test for this method to make sure all of the parameterizations each pass the test but I ran the tests for `kernel=None` and they all pass so nothing to worry about now. 

The Wills and Meyer paper mentions using the k smallest eigenvalues for the Laplacian. If I read this right, this method is using the largest k eigenvalues. Is that an issue?

**Comment by gstonge** [comment]
Very interesting, didn't realized that Wills and Meyer considered the k smallest eigenvalues. [Masuda and Holme](https://www.nature.com/articles/s41598-018-37534-2) and [Jurman et al.](https://arxiv.org/pdf/1005.0103.pdf) suggest using the largest ones. I don't know enough about the spectra of graph to interpret what information the smallest/largest eigenvalues of the Laplacian convey.

Should we allow for both with another option? It would be really simple to add since the function `scipy.sparse.linalg.eigsh` used to compute the k eigenvalues has the option "SM" for smallest in magnitude.

**Comment by sdmccabe** [comment]
I'm pretty agnostic on this; maybe @leotrs has opinions. I think this is good to merge and we can revisit the largest/smallest issue separately. Thanks for implementing this!

**Comment by leotrs** [comment]
I have come and I have brought my opinions. Different parts of the spectrum contain different kinds of information. Each different method should justify why they use the part of the spectrum they use. As a general rule, I think we should just implement what original authors have implemented and cite them for justification. Code-wise I think it's best to allow for both, for flexibility.

I'll point out here that using `scipy.sparse.linalg.eighs` with `which='SM'` is not the most efficient way to go. The most efficient is probably to use [shift-invert mode](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html#shift-invert-mode). However, let's implement that only when/if this starts becoming a bottleneck. (Which will happen if there are lots of eigenvalues that are very very small.) So for now let's just do `which='SM'` and cross fingers.

**Pull request merged**
